INSERT INTO country VALUES ('IDN', 'Indonesia');
INSERT INTO country VALUES ('PRT', 'Portugal');
INSERT INTO country VALUES ('QAT', 'Qatar');
INSERT INTO country VALUES ('NZL', 'New Zealand');
INSERT INTO country VALUES ('JPN', 'Japan');
INSERT INTO country VALUES ('BEL', 'Belgium');
INSERT INTO country VALUES ('CHN', 'China');
INSERT INTO country VALUES ('PRK', 'Korea');
INSERT INTO country VALUES ('CAN', 'Canada');
INSERT INTO country VALUES ('AUS', 'Australia');

INSERT INTO city VALUES ('JKT', 'Jakarta', 'IDN');
INSERT INTO city VALUES ('DPS', 'Denpasar', 'IDN');
INSERT INTO city VALUES ('SYD', 'Sydney', 'AUS');
INSERT INTO city VALUES ('BAE', 'Beijing', 'CHN');
INSERT INTO city VALUES ('YYZ', 'Toronto', 'CAN');
INSERT INTO city VALUES ('ICN', 'Seoul', 'PRK');
INSERT INTO city VALUES ('NRT', 'Narita', 'JPN');
INSERT INTO city VALUES ('AKL', 'Auckland', 'NZL');
INSERT INTO city VALUES ('ANR', 'Antwerp', 'BEL');
INSERT INTO city VALUES ('LIS', 'Lisbon', 'PRT');

INSERT INTO contactdetail VALUES ('CD01', 'sophia.langham@gmail.com', '+629842135678', '123 Elm Street, Springfield', 'YYZ');
INSERT INTO contactdetail VALUES ('CD02', 'jorda.jane@gmail.com', '+612345678901', '456 Oak Street', 'SYD');
INSERT INTO contactdetail VALUES ('CD03', 'selly.hartono@gmail.com', '+723456789012', '36 Raden Patah road', 'DPS');
INSERT INTO contactdetail VALUES ('CD04', 'emily.brown@gmail.com', '4567890123', '101 Maple Avenue', 'AKL');
INSERT INTO contactdetail VALUES ('CD05', 'vivian.lee@gmail.com', '+52678901234', 'Beijing street 45', 'BAE');
INSERT INTO contactdetail VALUES ('CD06', 'feroline.lim@gmail.com', '+61678901258', '303 Cedar Drive', 'ANR');
INSERT INTO contactdetail VALUES ('CD07', 'david.kim@gmail.com', '+4378901237', '404 Ash Lane', 'ICN');
INSERT INTO contactdetail VALUES ('CD08', 'evan.huang@gmail.com', '+1901274364', 'Spruce street', 'NRT');
INSERT INTO contactdetail VALUES ('CD09', 'matthew.william@gmail.com', '+8901638524', '606 Palm Road', 'LIS');
INSERT INTO contactdetail VALUES ('CD10', 'michael.terence@gmail.com', '+6138656464', '701 Cedar Avenue', 'JKT');
INSERT INTO contactdetail VALUES ('CD11', 'aisha.mohammed@gmail.com', '+201234567890', '789 Pine Street, Cairo', 'JKT');
INSERT INTO contactdetail VALUES ('CD12', 'lucas.martinez@gmail.com', '+54174268990', '1011 Birch Road, Buenos Aires', 'BAE');
INSERT INTO contactdetail VALUES ('CD13', 'olivia.rodriguez@gmail.com', '+5274283568', '202 Willow Avenue, Mexico City', 'NRT');
INSERT INTO contactdetail VALUES ('CD14', 'alexander.ivanov@gmail.com', '+79144633237', '303 Elm Street, Moscow', 'ICN');
INSERT INTO contactdetail VALUES ('CD15', 'maria.rossi@gmail.com', '+39722568965', '404 Chestnut Boulevard, Rome', 'FCO');
INSERT INTO contactdetail VALUES ('CD16', 'yuki.nakamura@gmail.com', '+8112345863', '505 Magnolia Drive, Tokyo', 'DPS');
INSERT INTO contactdetail VALUES ('CD17', 'hans.schmidt@gmail.com', '+49248997543', '606 Alder Road, Berlin', 'LIS');
INSERT INTO contactdetail VALUES ('CD18', 'fatima.al-salem@gmail.com', '+96053211076', '707 Fir Street, Riyadh', 'NRT');
INSERT INTO contactdetail VALUES ('CD19', 'john.smith@gmail.com', '+11267575638', '808 Poplar Street, New York', 'ANR');
INSERT INTO contactdetail VALUES ('CD20', 'linda.miller@gmail.com', '+44835698724', '909 Aspen Lane, London', 'YYZ');

INSERT INTO officebranch VALUES ('B01', 'New Lisbon', 'New Lisbon Road no 143', 'LIS');
INSERT INTO officebranch VALUES ('B02', 'West Side Beijing', 'Beijing street 123', 'BAE');
INSERT INTO officebranch VALUES ('B03', 'East Denpasar', '17 Majapahit road', 'DPS');
INSERT INTO officebranch VALUES ('B04', 'Narita Northern Branch', 'North coast lane 53', 'NRT');
INSERT INTO officebranch VALUES ('B05', 'Auckland Central Branch', 'Central Ave 987', 'AKL');
INSERT INTO officebranch VALUES ('B06', 'Jakarta Branch', 'Kembang sari road 23', 'JKT');
INSERT INTO officebranch VALUES ('B07', 'Central Park Sydney', 'Sydney central 35', 'SYD');
INSERT INTO officebranch VALUES ('B08', 'River Side', 'Seoul river side 23', 'ICN');
INSERT INTO officebranch VALUES ('B09', 'Antwerp Old Town', '145 Old town road', 'ANR');
INSERT INTO officebranch VALUES ('B10', 'Downtown Toronto', 'Maison street 673', 'YYZ');

INSERT INTO flightstaff VALUES ('S01', 'John Michael', 'Pilot', 'john.michael@gmail.com', 'B02');
INSERT INTO flightstaff VALUES ('S02', 'Mason James Harlow', 'Pilot', 'mason.carlow@gmail.com', 'B01');
INSERT INTO flightstaff VALUES ('S03', 'Avery Cora', 'Co-Pilot', 'avery.cora@gmail.com', 'B06');
INSERT INTO flightstaff VALUES ('S04', 'Benjamin Michael', 'Co-Pilot', 'benjamin.michael@gmail.com', 'B05');
INSERT INTO flightstaff VALUES ('S05', 'Riley Emerson', 'Senior Flight Attendant', 'riley.emerson@gmail.com', 'B03');
INSERT INTO flightstaff VALUES ('S06', 'Amelia Jordan Phoenix', 'Senior Flight Attendant',  'amelia.phoenix@gmail.com', 'B10');
INSERT INTO flightstaff VALUES ('S07', 'Shaneen Vanessa Lee', 'Flight Attendant', 'shaneen.lee@gmail.com', 'B09');
INSERT INTO flightstaff VALUES ('S08', 'Angelique Carmen', 'Flight Attendant',  'angelique.carmen@gmail.com', 'B09');
INSERT INTO flightstaff VALUES ('S09', 'Isla Debora', 'Flight Attendant', 'isla.debora@gmail.com', 'B04');
INSERT INTO flightstaff VALUES ('S10', 'Sophia Grace', 'Flight Attendant', 'sophia.grace@gmail.com', 'B07');
INSERT INTO flightstaff VALUES ('S11', 'Daniel Henry', 'Pilot', 'daniel.henry@gmail.com', 'B08');
INSERT INTO flightstaff VALUES ('S12', 'Madison Ava', 'Pilot', 'madison.ava@gmail.com', 'B01');
INSERT INTO flightstaff VALUES ('S13', 'Lucas Ethan', 'Co-Pilot', 'lucas.ethan@gmail.com', 'B01');
INSERT INTO flightstaff VALUES ('S14', 'Olivia Isabella', 'Co-Pilot', 'olivia.isabella@gmail.com', 'B05');
INSERT INTO flightstaff VALUES ('S15', 'Ella Marie', 'Senior Flight Attendant', 'ella.marie@gmail.com', 'B06');
INSERT INTO flightstaff VALUES ('S16', 'Liam Alexander', 'Senior Flight Attendant', 'liam.alexander@gmail.com', 'B03');
INSERT INTO flightstaff VALUES ('S17', 'Charlotte Sophia', 'Flight Attendant', 'charlotte.sophia@gmail.com', 'B10');
INSERT INTO flightstaff VALUES ('S18', 'Mia Elizabeth', 'Flight Attendant', 'mia.elizabeth@gmail.com', 'B04');
INSERT INTO flightstaff VALUES ('S19', 'Aiden James', 'Flight Attendant', 'aiden.james@gmail.com', 'B07');
INSERT INTO flightstaff VALUES ('S20', 'Harper Amelia', 'Flight Attendant', 'harper.amelia@gmail.com', 'B09');

INSERT INTO airplane VALUES ('A01', 'A1256', '150');
INSERT INTO airplane VALUES ('A02', 'B7856', '180');
INSERT INTO airplane VALUES ('A03', 'A9451', '200');
INSERT INTO airplane VALUES ('A04', 'K4327', '160');
INSERT INTO airplane VALUES ('A05', 'F1819', '190');
INSERT INTO airplane VALUES ('A06', 'A2341', '160');
INSERT INTO airplane VALUES ('A07', 'E1515', '250');
INSERT INTO airplane VALUES ('A08', 'C4363', '275');
INSERT INTO airplane VALUES ('A09', 'X7374', '300');
INSERT INTO airplane VALUES ('A10', 'Z1259', '320');

INSERT INTO fine VALUES ('F01', 'Ticket Cancellation', '50');
INSERT INTO fine VALUES ('F02', 'No show', '100');
INSERT INTO fine VALUES ('F03', 'Baggage overweight', '75');
INSERT INTO fine VALUES ('F04', 'Change of flight', '50');
INSERT INTO fine VALUES ('F05', 'Seat upgrade', '150');
INSERT INTO fine VALUES ('F06', 'Excessive luggage', '20');
INSERT INTO fine VALUES ('F07', 'Name change', '20');
INSERT INTO fine VALUES ('F08', 'Priority boarding', '30');
INSERT INTO fine VALUES ('F09', 'Flight date change', '50');
INSERT INTO fine VALUES ('F10', 'Pet travel', '160');

INSERT INTO flight VALUES ('FL01', 'Lisbon', 'Seoul', 'FTH567');
INSERT INTO flight VALUES ('FL02', 'Jakarta', 'Denpasar', 'ABT983');
INSERT INTO flight VALUES ('FL03', 'Beijing', 'Sydney', 'LKM345');
INSERT INTO flight VALUES ('FL04', 'Denpasar', 'Seoul', 'PQR789');
INSERT INTO flight VALUES ('FL05', 'Sydney', 'Auckland', 'XYZ364');
INSERT INTO flight VALUES ('FL06', 'Narita', 'Toronto', 'JKL980');
INSERT INTO flight VALUES ('FL07', 'Lisbon', 'Antwerp', 'DEF500');
INSERT INTO flight VALUES ('FL08', 'Antwerp', 'Seoul', 'MNO177');
INSERT INTO flight VALUES ('FL09', 'Auckland', 'Jakarta', 'GHI421');
INSERT INTO flight VALUES ('FL10', 'Toronto', 'Seoul', 'UVW890');

INSERT INTO passenger VALUES ('P01', 'Sophia Beth Langham', '19', 'Armenian', 'CD01');
INSERT INTO passenger VALUES ('P02', 'Jorda Jane', '53', 'Canadian', 'CD02');
INSERT INTO passenger VALUES ('P03', 'Selly Hartono', '21', 'Indonesian', 'CD03');
INSERT INTO passenger VALUES ('P04', 'Emily Brown', '25', 'Australian', 'CD04');
INSERT INTO passenger VALUES ('P05', 'Naomi Vivian Lee', '22', 'Singaporean', 'CD05');
INSERT INTO passenger VALUES ('P06', 'Feroline Lim', '26', 'Malaysian', 'CD06');
INSERT INTO passenger VALUES ('P07', 'David Kim', '35', 'Korean', 'CD07');
INSERT INTO passenger VALUES ('P08', 'Evan Huang', '51', 'Chinese', 'CD08');
INSERT INTO passenger VALUES ('P09', 'Matthew William', '33', 'Swedish', 'CD09');
INSERT INTO passenger VALUES ('P10', 'Michael Terence', '46', 'Belgian', 'CD10');
INSERT INTO passenger VALUES ('P11', 'Aisha Mohammed', '28', 'Egyptian', 'CD11');
INSERT INTO passenger VALUES ('P12', 'Lucas Martinez', '41', 'Argentinian', 'CD12');
INSERT INTO passenger VALUES ('P13', 'Olivia Rodriguez', '30', 'Mexican', 'CD13');
INSERT INTO passenger VALUES ('P14', 'Alexander Ivanov', '37', 'Russian', 'CD14');
INSERT INTO passenger VALUES ('P15', 'Maria Rossi', '32', 'Italian', 'CD15');
INSERT INTO passenger VALUES ('P16', 'Yuki Nakamura', '29', 'Japanese', 'CD16');
INSERT INTO passenger VALUES ('P17', 'Hans Schmidt', '44', 'German', 'CD17');
INSERT INTO passenger VALUES ('P18', 'Fatima Al-Salem', '23', 'Saudi Arabian', 'CD18');
INSERT INTO passenger VALUES ('P19', 'John Smith', '50', 'American', 'CD19');
INSERT INTO passenger VALUES ('P20', 'Linda Miller', '38', 'British', 'CD20');

INSERT INTO sales VALUES ('SL01', 'Early bird booking', '50');
INSERT INTO sales VALUES ('SL02', 'Senior citizen discount', '60');
INSERT INTO sales VALUES ('SL03', 'Student discount', '25');
INSERT INTO sales VALUES ('SL04', 'Military discount', '40');
INSERT INTO sales VALUES ('SL05', 'Group booking discount', '100');
INSERT INTO sales VALUES ('SL06', 'Frequent flyer discount', '45');
INSERT INTO sales VALUES ('SL07', 'Holiday Special discount', '50');
INSERT INTO sales VALUES ('SL08', 'Gold member', '70');
INSERT INTO sales VALUES ('SL09', 'Silver member', '55');
INSERT INTO sales VALUES ('SL10', 'Family package discount', '75');

INSERT INTO ticketprice VALUES ('TP01', '375', 'FL01');
INSERT INTO ticketprice VALUES ('TP02', '123.4', 'FL02');
INSERT INTO ticketprice VALUES ('TP03', '78', 'FL03');
INSERT INTO ticketprice VALUES ('TP04', '100', 'FL04');
INSERT INTO ticketprice VALUES ('TP05', '200', 'FL05');
INSERT INTO ticketprice VALUES ('TP06', '98.7', 'FL06');
INSERT INTO ticketprice VALUES ('TP07', '101.5', 'FL07');
INSERT INTO ticketprice VALUES ('TP08', '84', 'FL08');
INSERT INTO ticketprice VALUES ('TP09', '175', 'FL09');
INSERT INTO ticketprice VALUES ('TP10', '166', 'FL10');

INSERT INTO schedule VALUES ('SC01', TO_TIMESTAMP('2024-01-23 20:13', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-01-24 02:11', 'YYYY-MM-DD HH24:MI'), 'A01', 'TP05');
INSERT INTO schedule VALUES ('SC02', TO_TIMESTAMP('2024-03-04 09:30', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-03-04 11:34', 'YYYY-MM-DD HH24:MI'), 'A06', 'TP06');
INSERT INTO schedule VALUES ('SC03', TO_TIMESTAMP('2024-06-06 00:14', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-06-06 06:55', 'YYYY-MM-DD HH24:MI'), 'A08', 'TP04');
INSERT INTO schedule VALUES ('SC04', TO_TIMESTAMP('2024-10-30 11:22', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-10-30 15:45', 'YYYY-MM-DD HH24:MI'), 'A02', 'TP03');
INSERT INTO schedule VALUES ('SC05', TO_TIMESTAMP('2024-11-23 17:21', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-11-23 23:11', 'YYYY-MM-DD HH24:MI'), 'A07', 'TP01');
INSERT INTO schedule VALUES ('SC06', TO_TIMESTAMP('2024-07-17 09:13', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-07-17 13:14', 'YYYY-MM-DD HH24:MI'), 'A10', 'TP10');
INSERT INTO schedule VALUES ('SC07', TO_TIMESTAMP('2024-02-21 09:45', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-02-21 16:00', 'YYYY-MM-DD HH24:MI'), 'A05', 'TP03');
INSERT INTO schedule VALUES ('SC08', TO_TIMESTAMP('2024-03-15 18:30', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-03-16 00:10', 'YYYY-MM-DD HH24:MI'), 'A04', 'TP09');
INSERT INTO schedule VALUES ('SC09', TO_TIMESTAMP('2024-05-31 08:00', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-05-31 14:50', 'YYYY-MM-DD HH24:MI'), 'A03', 'TP10');
INSERT INTO schedule VALUES ('SC10', TO_TIMESTAMP('2024-11-11 21:14', 'YYYY-MM-DD HH24:MI'), TO_TIMESTAMP('2024-11-12 02:34', 'YYYY-MM-DD HH24:MI'), 'A09', 'TP08');

INSERT INTO transaction VALUES ('T01', NULL, 'SL01', 'P01', 'SC01', 'S02');
INSERT INTO transaction VALUES ('T02', NULL, 'SL03', 'P10', 'SC02', 'S10');
INSERT INTO transaction VALUES ('T03', 'F02', NULL, 'P02', 'SC03', 'S01');
INSERT INTO transaction VALUES ('T04', 'F04', 'SL09', 'P03', 'SC04', 'S03');
INSERT INTO transaction VALUES ('T05', 'F05', NULL, 'P04', 'SC05', 'S04');
INSERT INTO transaction VALUES ('T06', 'F06', NULL, 'P05', 'SC06', 'S05');
INSERT INTO transaction VALUES ('T07', NULL, 'SL04', 'P06', 'SC07', 'S06');
INSERT INTO transaction VALUES ('T08', 'F08', NULL, 'P07', 'SC08', 'S07');
INSERT INTO transaction VALUES ('T09', 'F09', NULL, 'P08', 'SC09', 'S08');
INSERT INTO transaction VALUES ('T10', 'F10', NULL, 'P09', 'SC10', 'S09');
INSERT INTO transaction VALUES ('T11', NULL, 'SL01', 'P11', 'SC01', 'S02');
INSERT INTO transaction VALUES ('T12', 'F09', 'SL03', 'P12', 'SC02', 'S10');
INSERT INTO transaction VALUES ('T13', 'F02', NULL, 'P13', 'SC03', 'S01');
INSERT INTO transaction VALUES ('T14', 'F04', 'SL09', 'P14', 'SC04', 'S03');
INSERT INTO transaction VALUES ('T15', 'F05', 'SL01', 'P15', 'SC05', 'S04');
INSERT INTO transaction VALUES ('T16', 'F06', NULL, 'P16', 'SC06', 'S05');
INSERT INTO transaction VALUES ('T17', NULL, 'SL04', 'P17', 'SC07', 'S06');
INSERT INTO transaction VALUES ('T18', 'F08', NULL, 'P18', 'SC08', 'S07');
INSERT INTO transaction VALUES ('T19', 'F09', NULL, 'P19', 'SC09', 'S08');
INSERT INTO transaction VALUES ('T20', 'F10', 'SL03', 'P20', 'SC10', 'S09');





